name: Update README with Latest Medium Article

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Uses Node.js 20 by default
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet
      
    - name: Fetch Medium RSS Feed and Extract Titles and Links
      run: |
        # Fetch the latest articles from Medium RSS feed
        curl -s https://medium.com/feed/@shaswat.srivastava.404 | xmlstarlet sel -t -m '//item' -v 'concat(title, "|", link)' -n | head -n 5 > latest_articles.txt
        echo "Contents of latest_articles.txt:"
        cat latest_articles.txt

    - name: Format and Update README
      run: |
        # Read the latest articles
        LATEST_ARTICLES=$(cat latest_articles.txt)
        echo "Latest articles content: $LATEST_ARTICLES"

        # Initialize formatted articles variable
        FORMATTED_ARTICLES=""
        
        # Fetch and format each article title and link
        while IFS= read -r line; do
          TITLE=$(echo "$line" | cut -d '|' -f 1 | sed 's/<!\[CDATA\[//g' | sed 's/\]\]>//g')
          LINK=$(echo "$line" | cut -d '|' -f 2)
          FORMATTED_ARTICLES="$FORMATTED_ARTICLES\n- [$TITLE]($LINK)"
        done <<< "$LATEST_ARTICLES"
        
        echo "Formatted articles: $FORMATTED_ARTICLES"

        # Update the README.md file
        README_CONTENT=$(cat README.md)
        UPDATED_README=$(echo "$README_CONTENT" | sed -e '/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\<!-- BLOG-POST-LIST:START -->\n'"$FORMATTED_ARTICLES"'\n<!-- BLOG-POST-LIST:END -->')
        echo "$UPDATED_README" > README.md
        
        echo "Updated README content: $UPDATED_README"

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m 'Update README with latest Medium articles'
        git push origin HEAD:main

    - name: Clean up
      run: |
        rm latest_articles.txt
